#!/usr/bin/env python3
"""
make_signal_data.py -- regenerate hardware/signal_data.h for STM32 v19.

CHANGES FROM THE v18 HEADER
  length   1,000 -> 10,000 samples per signal
           At buffer 4096 a 1,000-sample signal produces ZERO evictions,
           so the old header could not exercise the large-buffer region
           where the heap is expected to win. 10,000 gives 5,904
           evictions at buffer 4096.

  type     float32 -> int16 + per-signal float scale
           Three reasons:
           1. Flash. 6 x 10,000 x 4 B = 240 KB of 512 KB as float;
              int16 halves that to 120 KB.
           2. Honesty. The source is a 12-bit / 16-bit ADC. Storing
              float32 samples means the "compressed" output is WIDER
              than the input, which is why the reported compression
              ratio came out at 0.68x -- i.e. expansion. 2 x 16/48
              = 0.667. That was the bug.
           3. It is what a real front end does: one gain per channel.

           Scale = max|x| / 32767 per signal, so each uses the full
           int16 range. Reconstruct as  value = raw * scale.

  signals  ecg100, ecg105, vib_normal, vib_inner, sine, har_mixed
           har_mixed concatenates walking + walking_up + walking_down
           (6,400 each) because no single UCI HAR activity file is
           long enough. Real 50 Hz accelerometer with gait transitions;
           labelled "mixed" rather than passed off as one recording.

QUANTISATION COST
  Reported per signal as the SNR of the int16 representation against
  the float original. Expect >90 dB; anything lower means the signal
  has an outlier compressing the useful range and needs checking.

Output: hardware/signal_data.h
"""

import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
N = 10000
OUT = os.path.join(ROOT, "hardware", "signal_data.h")

SOURCES = [
    ("ecg100",     ["data/mit-bih/ecg_100.txt"],                    "MIT-BIH record 100, 360 Hz"),
    ("ecg105",     ["data/mit-bih/ecg_105.txt"],                    "MIT-BIH record 105, 360 Hz"),
    ("vib_normal", ["data/cwru-bearing/vib_Normal_0.txt"],          "CWRU normal baseline, 12 kHz"),
    ("vib_inner",  ["data/cwru-bearing/vib_IR007_0.txt"],           "CWRU inner race 0.007in, 12 kHz"),
    ("har_mixed",  ["data/uci-har/processed/har_walking.txt",
                    "data/uci-har/processed/har_walking_up.txt",
                    "data/uci-har/processed/har_walking_down.txt"], "UCI HAR walk/up/down, 50 Hz"),
]


def load_concat(paths, n):
    out = []
    for p in paths:
        f = os.path.join(ROOT, p)
        if not os.path.exists(f):
            return None, f"missing {p}"
        out.append(np.loadtxt(f))
        if sum(len(a) for a in out) >= n:
            break
    x = np.concatenate(out)
    if len(x) < n:
        return None, f"only {len(x)} samples, need {n}"
    return x[:n], None


def synth_sine(n):
    """Deterministic two-tone reference. Same formula as v18 main.c."""
    i = np.arange(n)
    return (np.sin(2 * np.pi * 5.0 * i / n)
            + 0.3 * np.sin(2 * np.pi * 13.0 * i / n))


def quantise(x):
    peak = float(np.max(np.abs(x)))
    if peak <= 0:
        return np.zeros(len(x), dtype=np.int16), 1.0, float("inf")
    scale = peak / 32767.0
    q = np.clip(np.round(x / scale), -32768, 32767).astype(np.int16)
    err = x - q.astype(np.float64) * scale
    ep = float(np.sum(err ** 2))
    snr = 10 * np.log10(float(np.sum(x ** 2)) / ep) if ep > 0 else float("inf")
    return q, scale, snr


def main():
    sigs, problems = [], []

    for name, paths, desc in SOURCES:
        x, err = load_concat(paths, N)
        if x is None:
            problems.append(f"{name}: {err}")
            continue
        sigs.append((name, x, desc))

    sigs.insert(4, ("sine", synth_sine(N), "Synthetic two-tone, 5 Hz + 0.3x13 Hz"))

    if problems:
        print("PROBLEMS:")
        for p in problems:
            print("  -", p)
        if not sigs:
            sys.exit(1)
        print()

    lines = [
        "#ifndef SIGNAL_DATA_H",
        "#define SIGNAL_DATA_H",
        "",
        "/* Generated by scripts/make_signal_data.py -- do not edit by hand.",
        " *",
        " * Samples are int16, as delivered by a 16-bit ADC front end.",
        " * Reconstruct engineering units as:  value = (float)raw * <name>_scale",
        " *",
        " * Storing float32 here would make the compressed output wider than",
        " * the acquired input, which is the arithmetic error behind the",
        " * previously reported 0.68x compression ratio.",
        " */",
        "",
        "#include <stdint.h>",
        "",
        f"#define SIGNAL_LEN {N}",
        f"#define NUM_SIGNALS {len(sigs)}",
        "",
    ]

    print(f"{'signal':<12} {'peak':>12} {'scale':>14} {'quant SNR':>11}  source")
    print("-" * 78)

    names = []
    for name, x, desc in sigs:
        q, scale, snr = quantise(x)
        names.append(name)
        print(f"{name:<12} {np.max(np.abs(x)):>12.6f} {scale:>14.6e} "
              f"{snr:>10.1f} dB  {desc}")
        if snr < 80:
            print(f"  WARNING: {name} quantisation SNR is low -- check for outliers")

        lines.append(f"/* {desc} */")
        lines.append(f"static const float {name}_scale = {scale:.9e}f;")
        lines.append(f"static const int16_t {name}[{N}] = {{")
        for i in range(0, N, 16):
            chunk = ",".join(f"{v:6d}" for v in q[i:i + 16])
            lines.append("    " + chunk + ",")
        lines.append("};")
        lines.append("")

    # Dispatch table so main.c can loop over signals.
    lines.append("static const int16_t* const SIGNALS[NUM_SIGNALS] = {")
    lines.append("    " + ", ".join(names))
    lines.append("};")
    lines.append("static const float SIGNAL_SCALES[NUM_SIGNALS] = {")
    lines.append("    " + ", ".join(f"{n}_scale" for n in names))
    lines.append("};")
    lines.append("static const char* const SIGNAL_NAMES[NUM_SIGNALS] = {")
    lines.append("    " + ", ".join(f'"{n}"' for n in names))
    lines.append("};")
    lines.append("")
    lines.append("#endif /* SIGNAL_DATA_H */")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    kb = os.path.getsize(OUT) / 1024
    flash = len(sigs) * N * 2 / 1024
    print(f"\nWrote {OUT}")
    print(f"  header size: {kb:.0f} KB text")
    print(f"  flash usage: {flash:.0f} KB of 512 KB "
          f"({len(sigs)} signals x {N} x 2 B)")
    print(f"\n  At buffer 4096: {N - 4096} evictions per run.")
    print(f"  At buffer 512:  {N - 512} evictions per run.")


if __name__ == "__main__":
    main()
